### ISSUE TITLE
Code Benchmarking: JMH8

### ISSUE THREAD

**Issue by david-pellissier** [gen-classroom/projet-pellissier_ruckstuhl_sauge_viotti-prsv#108]

**Comment by rya-sge** [comment]
Utilisez JMH8 pour mesurer les performances de votre compilateur markdown ou de votre moteur de rendu.

**Comment by rya-sge** [comment]
Utilisez JMH8 pour mesurer les performances de votre compilateur markdown ou de votre moteur de rendu.
