### ISSUE TITLE
Code Benchmarking: VisualVM9

### ISSUE THREAD

**Issue by david-pellissier** [gen-classroom/projet-pellissier_ruckstuhl_sauge_viotti-prsv#118]

**Comment by rya-sge** [comment]
Utilisez VisualVM9 pour profiler une exécution de la commande build. Incluez ces données dans votre rapport et discutez d’une éventuelle optimisation (sans nécessairement l’implémenter).

**Comment by david-pellissier** [comment]
J'ai testé mais il ne semble pas être possible de lancer une application depuis VisualVM9 directement. VVM9 doit se connecter sur un PID déjà en exécution. 
Ce qui veut dire qu'il faut attendre d'avoir l'option `--watch` sur la commande Build pour pouvoir s'y connecter depuis VisualVM9

**Comment by david-pellissier** [comment]
En fait j'avais pas assez cherché: https://visualvm.github.io/startupprofiler.html

**Comment by david-pellissier** [comment]
Pas besoin de PR pour ça, mais c'est fait: il y a un tuto sur comment l'utiliser pour se connecter à Statique sur le document du sprint
